---
title: "[멋쟁이사자처럼] OBG의 TIL 페이지 개설"
description: |
    Socar Bootcamp Peer Group OBG(Old But Gold)의 TIL 페이지입니다.
author:
  - name: nackta
date: 2022-05-13
preview: images/owl.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

`r emo::ji("bow")`안녕하세요. OBG의 Peer Group Leader 김경환입니다. 어쩌다보니 leader를 맡게 되었는데 부족하지만 알찬 스터디가 되도록 노력하겠습니다.

## `r emo::ji("lion")`PG 필수 공통활동

### `r emo::ji("keycap_1")`주 1회 이상 study 및 TIL작성

OBG는 일요일에 시간을 맞춰 스터디를 진행할 예정입니다. 일주일동안 정해진 공부한 내용을 각자 스타일에 맞게 TIL을 작성 후 study 시간에 공유합니다. study를 하면서 어려웠던 점, 새로 알았던 점, 보충해야할 점 등을 파악하고 일주일동안 배운 내용을 회고하며 OBG의 TIL을 작성합니다. 마지막으로 차주 스터디 위한 계획을 공유하며 마무리합니다.

### `r emo::ji("keycap_2")`Peer Review

- [Peer Review Guide](https://likelion.notion.site/Peer-Review-Guide-981988d903cf4e85861dbcd0605179f3)를 읽어주세요.

- 코딩테스트나 대외비와 관련없는 데이터를 다루는 코드들은 github을 통해 상호 리뷰

## `r emo::ji("gold")`OBG만의 study 진행

### `r emo::ji("keycap_1")`밑바닥부터 시작하는 딥러닝

딥러닝의 근본이라고 할 수 있는 이 책을 매주 1 chapter씩 study합니다.

### `r emo::ji("keycap_2")`백준 코딩테스트 문제풀이

매주 정해진 문제를 풀고 peer review를 통해 서로의 코드를 발전시킵니다.

## `r emo::ji("technologist")`OBG 팀원 소개

- 김경환
    
    - 안녕하세요. 통계학과 졸업 후 작년 9월부터 올해 2월까지 한국전자통신연구원 인턴 경험을 통해 딥러닝에 관심이 생겼습니다. 잘 부탁드립니다!
    
    - [github](https://github.com/nackta)
    
    - [TIL 페이지](https://nackta.github.io/til.html)

- 최경석

    - 안녕하세요, 저는 산업경영공학부 3학년에 재학중인 최경석입니다. 머신러닝과 관련된 경험은 캐글이나 데이콘을 몇번 참가한적이 있고, 딥러닝은 한국조선해양에서 진행한 공모전에 간단한 이미지 분류를 진행한적이 있습니다. 교내 데이터 사이언스 학회에서도 활동하지만 개념적인 부분이 부족하고, 아직은 체득하지 못한 것 같아서 열심히 활동하며 배우고 싶습니다.
    
    - [github](https://github.com/kyle9909)
    
    - [TIL 페이지]

- 우선욱

    - [github]

    - [TIL 페이지]

- 류기철 

    - 안녕하세요 저는 리서치회사에 근무하고있는 류기철이라고 합니다. 현재 기본적인 ML/DL에 대한 기본적인 이론정도만 있어서 조금더 심화된 부분에 대한 실습을 하고싶어서 지원했습니다.
    
    - [github](https://github.com/ryugicheol)
    
    - [TIL 페이지]